### ISSUE TITLE
Define the API method needed for backend

### ISSUE THREAD

**Issue by jusabatier** [sigrennesmetropole/geor_urbanisme_mapstore#2]
Hello,

I think it would be great to define the needed API methods to implements for a backend to work with it.

The actual Urbanisme backend doesn't fit our needs, and we're developping another backend.
In order to make it work with this frontend mapstore plugin, we need to have a list of API's methods we have to implements.

Is it possible to list them ?

Also it will be great to make the backend API url customisable in config file.

**Comment by MaelREBOUX** [comment]
Hello Julien.

In my opinion what you require shoud be written in the developer documentation which currently blank : http://docs.georchestra.org/addon_urbanisme/guide_developpeur/index.html

I recommend to write something like the functions matrix of cadastrapp cf http://docs.georchestra.org/cadastrapp/guide_developpeur/index.html#matrice-des-fonctionnalites

**Comment by catmorales** [comment]
>I recommend to write something like the functions matrix of cadastrapp cf

I will try to do it now ,  it will correspond to the backend used in https://github.com/sigrennesmetropole/addon_urbanisme

**Comment by jusabatier** [comment]
After out meeting, the need is to have configurable backend APIs URL : 

backend.url=http://opendata.agglo-lepuyenvelay.fr/servitudes
cadastrapp.url=http://opendata.agglo-lepuyenvelay.fr/cadastrapp

Maybe you can allow to set those in a config file in the datadir (localConfig.json), or in the addon settings ?
