### ISSUE TITLE
Translations in french

### ISSUE THREAD

**Issue by sigrmed** [sigrennesmetropole/geor_urbanisme_mapstore#21]
Hello, 
The plugin has been translated in French  as "Town and Country Planning" but for our users this is not practical and we prefer the term "Urbanism".
Where can I change this translation?

**Comment by tdipisa** [comment]
@sigrmed which translations are you referring to preciselly? Can you please link the file in this repository?

**Comment by catmorales** [comment]
I refer to the label of the plugin : 
![image](https://user-images.githubusercontent.com/4659829/115352092-3da14b80-a1b7-11eb-9b4e-8847c5c1f75b.png)

**Comment by catmorales** [comment]
It's OK for me with the last update. We can close this issue.
