### ISSUE TITLE
Pictos for NRU and ADS buttons

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/geor_urbanisme_mapstore#22]
![image](https://user-images.githubusercontent.com/4659829/114190486-a5e86580-994b-11eb-8fef-7624eaa6c291.png)

As requested by @tdipisa  a few months ago, the pictograms to put on these two buttons should be:
* for NRU: a sheet of text as 
![image](https://user-images.githubusercontent.com/4659829/114191044-476fb700-994c-11eb-8129-3c39db5ccf34.png)

* for ADS: a construction crane or something reminiscent of construction (building permit, ...) as 
** ![image](https://user-images.githubusercontent.com/4659829/114192621-fd87d080-994d-11eb-8c38-055665291aaf.png)
** ![image](https://user-images.githubusercontent.com/4659829/114191518-cb29a380-994c-11eb-85f9-514ebad718f8.png)
** ![image](https://user-images.githubusercontent.com/4659829/114191718-05934080-994d-11eb-99ae-eb91941d134d.png)

**Comment by tdipisa** [comment]
@dsuren1 as soon as @allyoucanmap provide new icons, please apply them in the tool. Thank you.

**Comment by MaelREBOUX** [comment]
Any news on that point ?

**Comment by catmorales** [comment]
https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc3
deployed on test

**Comment by catmorales** [comment]
Plugin is not operationnal on portail-test

I have a problem with the request sended by urbanisme plugin to geoserver when clicking on e parcell (NRU function) .
https://portail-test.sig.rennesmetropole.fr/geoserver/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=__URBANISME_RASTER_LAYER__&layers=urbanisme_parcelle&query_layers=urbanisme_parcelle&x=51&y=51&height=101&width=101&srs=EPSG:3857&bbox=-183821.49839731326,6121418.8030470675,-183338.98965626306,6121901.311788118&feature_count=10&info_format=application%2Fjson&ENV=

We don't know what is  id=__URBANISME_RASTER_LAYER__

**Comment by catmorales** [comment]
I will check our data in database. I think we have problems with data.

**Comment by catmorales** [comment]
I confirm. It's OK now, we had a problem with the SLD of app: urbanisme_parcelle.

 I let @MaelREBOUX confirm that the evolutions are ok for him.

**Comment by MaelREBOUX** [comment]
it is fine

![image](https://user-images.githubusercontent.com/6370443/126126477-a2f729ad-9ba4-4b8f-a87a-398395a7723e.png)
