### ISSUE TITLE
[portail-test] Impossible to print NRU or ADS 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/geor_urbanisme_mapstore#23]
Clicking on the print functions does nothing.
Test with https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/cadastre-urbanisme

**Comment by tdipisa** [comment]
@dsuren1 are you able to reproduce the issue on GeoSolutions DEV instance?

**Comment by dsuren1** [comment]
Hi @tdipisa 
I'm unable to reproduce the issue in GeoSolutions [DEV ](https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp) instance. Able to print fine.

Hi @catmorales  Could you help us with a test account to access https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/cadastre-urbanisme and investigate the issue, at the least the configurations used for the plugin

**Comment by tdipisa** [comment]
@dsuren1 we can do a test with my account for the moment
@catmorales let me know anyway if you can create another account in your test environment for our developers.

**Comment by dsuren1** [comment]
Hi @catmorales 
With help from @tdipisa, we were able to reproduce the issue. Issue happen when printing the urbanisme layer with WMTS background.
I will work on the issue accordingly.

**Comment by catmorales** [comment]
>@catmorales let me know anyway if you can create another account in your test environment for our developers.

Sure , just submit an inscription and i will validate it

**Comment by catmorales** [comment]
>when printing the urbanisme layer with WMTS

Ok . All our base layers ar in WMTS services

**Comment by catmorales** [comment]
Great !
Could you please create the zip file ?
I will deploy it then in our test GeOrchestra?

**Comment by tdipisa** [comment]
@catmorales, @offtherailz will create the RC soon. Thank you.

**Comment by tdipisa** [comment]
@catmorales, the new zip is available [here](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/1.0.0-rc1)

**Comment by catmorales** [comment]
@tdipisa and @offtherailz thnk you very much, il will install it now

**Comment by catmorales** [comment]
II have just been tested and it is good for me. 
We can close this ticket.
Thank you very much.
