### ISSUE TITLE
Bogue si pas de droits Cadastrapp pour la commune / Bogue sur réponse JSON vide  |  Bug when no Cadastrapp rights for the municipality / Bug on empty JSON answer

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/geor_urbanisme_mapstore#31]
En utilisant un compte qui a un accès cadastrapp sur une commune uniquement, si on consulte une NRU sur une autre commune -> l'outil bogue et affiche la dernière NRU consultée.

While using an account who has a Cadastrapp access restricted only to one municipality, if one want to consult a NRU on another municipality -> the plugin bugs and show the last acceded NRU.

Dans l'animation ci-dessous la ligne rouge = limite communale.
1er clic = sud = commune autorisée par cadastrapp = OK
2e clic = nord = commune pas autorisée par cadastrapp = KO
Noter le message d'erreur en rouge.

In the animation below the red line = municipality frontier.
1st clic = south = authorised municipality = OK
2nd clic = north = authorised municipality by cadastrapp = KO
Note the red error message.

![ms2_bug_urbanisme_permissions_cadasrapp](https://user-images.githubusercontent.com/6370443/125753891-2240c72c-14c8-4d10-b4ce-fb73455368f0.gif)

L'affichage d'une NRU n'est PAS conditionnée aux droits CNIL1/2 de cadastrapp. 

Showing a NRU is NOT conditioned to the CNIL1/2 rights of Cadastrapp.

![capture_350](https://user-images.githubusercontent.com/6370443/125753814-0f3de6fd-2ee2-484c-82aa-8512c3688f3e.png)

Dans mapfishapp  / in Mapfishapp :

![capture_351](https://user-images.githubusercontent.com/6370443/125754399-51d41fd6-d88a-4f0a-8352-2215ba8b1b9a.png)

Il semblerait que le plugin plante sur la réponse à la requête `/cadastrapp/services/getFIC?parcelle=XXXXXX&onglet=1` qui est une réponse JSON vide quand l'utilisateur n'a pas les droits CNIL1/2 sur la commune.

It seems that the plugin hangs up on the answer of the request `/cadastrapp/services/getFIC?parcelle=XXXXXX&onglet=1` which is an empty JSON answer when the user has no CNIL1/2 rights on the municipality.

**Comment by tdipisa** [comment]
@MaelREBOUX I think we should be able to properly reproduce this in our [DEV environment](https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp). What provided in the description if not enough clear to us, I'm sorry.
Can you please provide necessary steps to reproduce it? Which is the current result and which should be the expected one for a precise location that can be identified in the map?

**Comment by tdipisa** [comment]
@MaelREBOUX any news for the above?

**Comment by MaelREBOUX** [comment]
Hello. I'm back.

1. create a new account on geOrchestra / use a dedicated user for the test
2. give it a role with a single municipality (ex : EL_COMM_RENNES)
3. load urbanisme plugin
4. clic in Rennes -> you should have a correct answer
5. clic in Cesson -> bug

Note : I don't know / can't remember what datas are in your DEV instance. Should I export you some fresh data for the urbanism plugin ? 


PS : cannot ask for a new account : there are errors in the console

**Comment by offtherailz** [comment]
I was able to replicate the issue in a similar way of the gif on our test env.
The area of the GIF is this:
![image](https://user-images.githubusercontent.com/1279510/126169742-24287719-8a05-4d07-82e9-ca240a542ae6.png)

In our environment we have only data of Rennes on certain tables, so the result is this:
- on mapfish app for admin user:
![urbanisme_31_mapfish](https://user-images.githubusercontent.com/1279510/126170032-c7a233fa-96ea-4d25-b8b0-93ad53c53977.gif)

As you can see the data remains from the old request. The same happens in MapStore, and because of the different dataset has the result you noticed. 

I'm going to fix it by forcing the clean up of the result, so the data should always be consistent.

**Comment by MaelREBOUX** [comment]
Hope so !

**Comment by offtherailz** [comment]
Please try https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc4

**Comment by MaelREBOUX** [comment]
Tested but it is not at all what we expect.

If you use the NRU tool you should be able to clic anywhere on the map to consult any NRU info on any parcel.
So, if the JSON answer from `/cadastrapp/services/getFIC?parcelle=XXXXXX&onglet=1` is empty => "Compte propriétaire" and "Propriétaire(s)" info cells will be blank / empty

![image](https://user-images.githubusercontent.com/6370443/126285039-dc756f5e-ac51-4ea7-81aa-a066c5feb68d.png)

That is why I wrote "Showing a NRU is NOT conditioned to the CNIL1/2 rights of Cadastrapp".

The image above is the result of a NRU on a parcel I have write to show owners. 
If I do not have a convenient cadastrapp role OR I have no cadastrap role =>empty JSON answer from the cadastrapp API => I see the NRU with Compte propriétaire" and "Propriétaire(s)" info cells blank / empty.

**Comment by tdipisa** [comment]
@MaelREBOUX please ensure to test the latest version of the plugin. We have provided a fix to always show what the backend service returns to the client: in the use case you mentioned, the results of the previous request / click were shown to the user. 

Below is a GIF that shows what we have with our user **tdipisa** that has the following roles (the link is private for you):
![image](https://user-images.githubusercontent.com/1280027/126297035-26b12e18-772c-468e-aad8-a1688b2b50a9.png)

https://drive.google.com/file/d/1WvJx3myIgRj8JDeIRc0pkdrEWlzfdzcZ/view?usp=sharing

Below is a GIF that shows the result of a click performed with our **testuser** with only the role EL_COMM_RENNES (the link is private for you):
![image](https://user-images.githubusercontent.com/1280027/126297246-a185b968-5d60-4451-8f4f-411993017491.png)

https://drive.google.com/file/d/1UgOJ1oJyYsHGLytpmfahmcD8d9dh8t6h/view?usp=sharing

Consider that we are data mostly for Rennes: as you can see from above GIFs, outside Rennes we have no data returned from the backend service.

**Comment by MaelREBOUX** [comment]
Soooooo..... Deployed RC4 in production for testing (you kow why...) and I get the same exactly behaviour as you show on the 2 gif.

But I rewrite what I write previously : if you use the NRU tool you should be able to clic anywhere on the map to consult any NRU info on any parcel. And if you are not allowed to acces to cadastre personnal datas, you'll not see owners infos.
Actually with RC4 we get a blank window with "No data to display" (+ "error to fetch data"). Even on our portal.

But this RC4 fix the bug wich display the previous NRU. Many thanks for that.

I prepared new datas for you : Rennes and Cesson-Sevigné. I cannot remember what was shipped for you last year.

**Comment by tdipisa** [comment]
Dear @MaelREBOUX
We don't need new data for this. The point here is quite easy to explain. 
If our plugin receives some empty response from the backend service, it reports an error with an empty message in the panel because some information are missing to populate the table

![image](https://user-images.githubusercontent.com/1280027/126458523-9da440bd-3a82-4576-b463-8e52e19e6bfe.png)

The old plugin in mapfishapp renders anyway the table with available information

![image](https://user-images.githubusercontent.com/1280027/126457863-67023e4d-0b50-498d-b20a-3c58fd094e8c.png)

We just need to fix this.

**Comment by offtherailz** [comment]
Ok, I found that the effective difference is handling `getCommune` returns an empty array.
In the screenshot of @MaelREBOUX also Commune is missing.
![image](https://user-images.githubusercontent.com/1279510/126461755-5f3bdd5b-7a88-4b63-9b99-11ecaa8b64cf.png)

This was an error for MapStore, avoiding this error, I have the same result of @tdipisa screenshot in MapStore, on our test env. 
![image](https://user-images.githubusercontent.com/1280027/126457863-67023e4d-0b50-498d-b20a-3c58fd094e8c.png)

So adding this should make the two application have the same behaviour in these cases. Going to send a PR for this

**Comment by offtherailz** [comment]
Here the new version, can you test it?

https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc5

**Comment by tdipisa** [comment]
@MaelREBOUX please let us know

**Comment by MaelREBOUX** [comment]
- [X]  with a user without any cadastrapp role : OK

![image](https://user-images.githubusercontent.com/6370443/126477949-a649a9e4-42c4-45c3-b3b3-a6681e9206e8.png)

- [X] with a user with a cadastrapp role only on a municipality

- [X] with a user with a cadastrapp role on all municipalities

Hurrah \o/

I discover the bug for the empty answer from cadastrapp for `/cadastrapp/services/getCommune?cgocommune=XXXXXX`. I'll create an issue for that. poke @pierrejego.
