### ISSUE TITLE
No NRU or ADS information in case of layer selection in the TOC

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/geor_urbanisme_mapstore#33]
**Platform** : https://portail-test.sig.rennesmetropole.fr
**Context** : https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/master-urba-foncier
In this application context identify tool is disabbled because it's a dedicated "urbanisme and foncier" context.

* select layer "Parcelles des grands propriétaires fonciers" in the TOC
* open "Urbanisme plugin"
* select NRU or ADS functionnality
* click on the map 
**Result** : There is no information 
**Expected** NRU or ADS information

Same behavior with a layer group selected.

We believe that when the NRU and ADS functions are activated, the click should provide their information sheet regardless of the layers selected in the TOC.
Closing the Urbanism plugin, restores the standard operation.

This is the behaviour observed in Cadastrapp.

**Comment by MaelREBOUX** [comment]
Linked to https://github.com/georchestra/mapstore2-cadastrapp/issues/134

**Comment by offtherailz** [comment]
@tdipisa I add these notes for developers, in order to get a starting point and to keep a report my investigation:
Actually urbanisme plugin uses Identify plugins functionalities (call for identify [action](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/blob/master/js/extension/epics/urbanisme.js#L177), wait for the epics of Identify plugin to [respond](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/blob/master/js/extension/epics/urbanisme.js#L279)). 

To avoid this problem, it should call directly the GFI [api](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/identify.jsx#L27) and process the response.

**Comment by MaelREBOUX** [comment]
So. Below what we meet actually :

![ms2_urbanisme_toc_layer_selection](https://user-images.githubusercontent.com/6370443/126170168-671370e6-1bce-441a-8a77-9f4e0532003a.gif)

**The "clic on the map to show NRU or ADS info" tool must be active as long as the urbanisme tool is loaded and must not be disturbed by the sélection of something in the TOC.**
This way we will have a similar behaviour as cadastrapp.


Is it more clear ?

**Comment by tdipisa** [comment]
@MaelREBOUX it was clear for us even before: the @offtherailz comment above is just a note for developers. Thank you anyway for clarifying further in the issue.

**Comment by MaelREBOUX** [comment]
It was not totally as reading it.  But I believe it explains why we have this kind of message while using another tool. The clic / indetify function is still in use.

![image](https://user-images.githubusercontent.com/6370443/126173084-2c857790-1c73-446f-abff-cddb2328333a.png)

**Comment by tdipisa** [comment]
>It was not totally sure as reading it. But I believe it explains why we have this kind of message while using another tool. The clic / indetify function is still in use.

This seems to be a different issue. I saw it is affecting your instance in portail-test while

**Comment by MaelREBOUX** [comment]
OK. It seems not related tu this plugin --> https://github.com/georchestra/mapstore2-georchestra/issues/408

**Comment by MaelREBOUX** [comment]
@tdipisa I deleted the messages that were related to our behaviour on our test portal and is out of the scope of this bug report. To not pollute the issue.

**Comment by catmorales** [comment]
corrected by #42

**Comment by MaelREBOUX** [comment]
Seems have corrected this bug.
