### ISSUE TITLE
Cannot deactivate the "clic on the map" tools / Toggle to identify tool or another tool

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/geor_urbanisme_mapstore#34]
Actually when you clic on one of the 2 buttons of the toolbar, you activate a tool but you cannot deactivate it by re-clic on the same tool.
In cadastrapp : we can do it as in the mapfishapp version.

![ms2_urbanisme_select_unselect](https://user-images.githubusercontent.com/6370443/126172579-24c6cef6-269a-4112-8bf6-5a5975193a02.gif)

![ms2_cadastrapp_select_unselect](https://user-images.githubusercontent.com/6370443/126172555-bb90b132-e26a-4585-8bed-2ce14a06b3d0.gif)

**Comment by tdipisa** [comment]
@MaelREBOUX thank you for reporting this.

**Comment by MaelREBOUX** [comment]
Sorry to not have notice that before.

**Comment by offtherailz** [comment]
Fix in RC6, please test
https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc6

**Comment by catmorales** [comment]
I've deployed in portail-test yet, it's OK for me for urbanisme .
 I'll reported it in production.
