### ISSUE TITLE
Missing localization traduction in the tooltip for HELP

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/geor_urbanisme_mapstore#40]
![image](https://user-images.githubusercontent.com/6370443/148739280-eca01611-0c0d-4b42-9603-564129ab5f4c.png)

Seems to miss a `help`entry in this file : https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/blob/2a6713122d2ae406903ebbdfe383cf715bf6c56f/assets/translations/data.fr-FR.json

Well : in all localization files indeed.

**Comment by offtherailz** [comment]
Released rc7 with this fix to test:
https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc7

**Comment by MaelREBOUX** [comment]
Thanks for the reactivity !

**Comment by tdipisa** [comment]
> Thanks for the reactivity !

you are welcome @MaelREBOUX. Feel free to close the issue then if all is good for you.

**Comment by catmorales** [comment]
@MaelREBOUX I have just deployed the rc7 on test portal.

**Comment by MaelREBOUX** [comment]
That's fine

![image](https://user-images.githubusercontent.com/6370443/149358469-b3e6eb19-e434-4f22-815c-744ef11e3f69.png)
