### ISSUE TITLE
Urbanisme Help Module for MapStore 

### ISSUE THREAD

**Issue by tdipisa** [sigrennesmetropole/geor_urbanisme_mapstore#5]
This button simply allows the user to reach the refence online documentatin of the tool. The URL of the documentation must be configurable as plugin configuration property.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/9ffa77dd-f00b-4612-95bc-50572022ebd7)

**Comment by MaelREBOUX** [comment]
Please point the url  to http://docs.georchestra.org/addon_urbanisme/
