### ISSUE TITLE
The map is moving when clicking on the map with the NRU tool

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/geor_urbanisme_mapstore#63]
Sometimes some users report us that the map is moving far away from the current work area just after clicking on the map with the NRU tool.

It was my case yesterday but impossible to reproduce today. But it is real.
So no animated gif to post below.

**Comment by catmorales** [comment]
Quickly behaviour seems like 'zoom to layer = true' on the catalog plugin when we add a layer from this application context at the first loading of the urbanisme layer (hidden) . We have to check this parameter in the application context.

**Comment by catmorales** [comment]
The parameter is on in urba-foncier context. So I think this issue has been resolved.
