### ISSUE TITLE
Stroke of the selected plot is not visible on the pdf file

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/geor_urbanisme_mapstore#65]
Versions : 

- MapStore2-geOrchestra	:[2022.02.00-geOrchestra](https://github.com/georchestra/mapstore2-georchestra/commits/2022.02.00-geOrchestra)[(f3ce6b9e)](https://github.com/georchestra/mapstore2georchestra/commit/f3ce6b9eb6f684bc0932b54af7738e965d8c26c2)
- MapStore2	:[2022.02.xx](https://github.com/geosolutions-it/MapStore2/commits/2022.02.xx)[(15c07932)](https://github.com/geosolutions-it/MapStore2/commit/15c079322f4ce44f73f957bd145a1bf209c695f2)
- Urbanisme front end release ( 2.1 release)

Issue:
![urbanisme_selected_plot_notvisible](https://user-images.githubusercontent.com/4659829/234652884-b55b4b05-176a-4b0b-8db0-b528a4cfb8c8.gif)

**Comment by catmorales** [comment]
@jusabatier Do you have the same behaviour on the 2.0 release ?
If it is the case, could it be linked to https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/pull/58 ?

**Comment by catmorales** [comment]
On the geosolution's demo site the map is not displayed on the pdf file:
![image](https://user-images.githubusercontent.com/4659829/234657976-1bf925c6-4527-4e24-81ec-147f1b6871f2.png)

**Comment by jusabatier** [comment]
It work well on our platform but I'm not sure if I've deployed the 2.0 version.

**Comment by catmorales** [comment]
OK this issue seems to be linked to the v2.1.0-rc release

**Comment by catmorales** [comment]
This issue has been resolved

**Comment by jusabatier** [comment]
Not here, testing last version of the plugin I get an error when printing : 

> Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
>     at 934.a9ed89a1.js:1:239937
>     at Object.map (934.a9ed89a1.js:1:240250)
>     at 934.a9ed89a1.js:1:234410
>     at Array.map (<anonymous>)
>     at ci (934.a9ed89a1.js:1:234360)
>     at pu (934.a9ed89a1.js:1:297691)
>     at 934.a9ed89a1.js:1:326549
>     at geOrchestra.js?be9117ff58373242e31a:2:4507600
>     at geOrchestra.js?be9117ff58373242e31a:2:4514069
>     at onClick (934.a9ed89a1.js:1:145361)
>     at onClick (934.a9ed89a1.js:1:129961)
>     at Object.m (geOrchestra.js?be9117ff58373242e31a:2:3674865)
>     at w (geOrchestra.js?be9117ff58373242e31a:2:3675008)
>     at geOrchestra.js?be9117ff58373242e31a:2:3675154
>     at C (geOrchestra.js?be9117ff58373242e31a:2:3675240)
>     at k (geOrchestra.js?be9117ff58373242e31a:2:3675689)

And nothing happen
